export const projects = [
  {
    id: '1',
    name: 'Solar Dashboard',
    category: 'Energy',
    price: 199,
    stock: 12,
    image: require('../assets/project1.png'),
    description: 'Smart solar monitoring solution for homes and small businesses.',
  },
  {
    id: '2',
    name: 'Fitness Tracker',
    category: 'Health',
    price: 129,
    stock: 8,
    image: require('../assets/project2.png'),
    description: 'Mobile app to track workouts, nutrition, and progress easily.',
  },
  {
    id: '3',
    name: 'Travel Planner',
    category: 'Lifestyle',
    price: 89,
    stock: 20,
    image: require('../assets/project3.png'),
    description: 'Plan trips, save itineraries, and organize travel details.',
  },
  {
    id: '4',
    name: 'E-commerce Shop',
    category: 'Retail',
    price: 299,
    stock: 5,
    image: require('../assets/project4.png'),
    description: 'Responsive online store with product categories and checkout.',
  },
  {
    id: '5',
    name: 'Recipe Book',
    category: 'Food',
    price: 49,
    stock: 15,
    image: require('../assets/project5.png'),
    description: 'Recipe collection app with search, favorites, and meal planning.',
  },
  {
    id: '6',
    name: 'Study Planner',
    category: 'Education',
    price: 79,
    stock: 10,
    image: require('../assets/project6.png'),
    description: 'Organize homework, exams, and study sessions in one place.',
  },
];
